import type { TenantConfig } from "./types";

const CAMERA_PERMISSION =
  "אפשר ל-$(PRODUCT_NAME) להשתמש במצלמה כדי לסרוק ברקודים ולצלם תמונות באפליקציה.";

const REQUIRED_PUBLIC_ENVIRONMENT_VARIABLES = [
  "EXPO_PUBLIC_API_AUTH_TOKEN",
  "EXPO_PUBLIC_SERVER",
  "EXPO_PUBLIC_TRAINER_PHONE_NUMBER",
  "EXPO_PUBLIC_CLOUDFRONT_URL",
  "EXPO_PUBLIC_MODE",
];

export const avihuTenant = {
  kind: "repository",
  id: "avihu",
  displayName: "Elevate Coach",
  slug: "avihu-team",
  owner: "avihuteam",
  version: "2.4.0",
  projectId: "bbbbb60d-eb47-48fb-a278-517aba8dcea2",
  updateUrl: "https://u.expo.dev/bbbbb60d-eb47-48fb-a278-517aba8dcea2",
  runtimeVersion: { policy: "appVersion" },
  orientation: "portrait",
  platforms: ["ios", "android"],
  assets: {
    legacy: false,
    icon: "./config/tenants/assets/avihu/generated/apple-icon.png",
    adaptiveIconForeground:
      "./config/tenants/assets/avihu/generated/android-adaptive-foreground.png",
    adaptiveIconBackgroundImage:
      "./config/tenants/assets/avihu/generated/android-adaptive-background.png",
    adaptiveIconBackgroundColor: "#FFFFFF",
    notificationIcon: "./config/tenants/assets/avihu/generated/notification-icon.png",
    notificationColor: "#ffffff",
    splash: "./config/tenants/assets/avihu/generated/splash.png",
    splashBackgroundColor: "#FFFFFF",
  },
  brand: {
    primaryColor: "#000000",
    backgroundColor: "#FFFFFF",
  },
  theme: {
    colors: {
      primary: "#072723",
      onPrimary: "#F8F8F8",
      secondary: "#EFF1F5",
      onSecondary: "#F8F8F8",
      accent: "#17B26A",
      onAccent: "#F8F8F8",
      primaryContainer: "#065f46",
      onPrimaryContainer: "#a7f3d0",
      secondaryContainer: "#25262A",
      onSecondaryContainer: "#e5e7eb",
      background: "#F8F8F8",
      onBackground: "#f8f9fa",
      surface: "#ffffffff",
      onSurface: "#e5e7eb",
      surfaceSubtle: "#F7F9F8",
      surfaceMuted: "#F2F2F2",
      surfaceVariant: "#4b5563",
      onSurfaceVariant: "#d1d5db",
      outline: "#D0D5DD",
      outlineVariant: "#4b5563",
      divider: "#E5E7EB",
      shadow: "#072723",
      shadowMuted: "#999999",
      scrim: "#000000",
      backdrop: "rgba(31, 41, 55, 0.4)",
      inverseSurface: "#e5e7eb",
      inverseOnSurface: "#1f2937",
      inversePrimary: "#10b981",
      success: "#17B26A",
      onSuccess: "#155724",
      successContainer: "#EDFFEB",
      onSuccessContainer: "#d4edda",
      warning: "#ffc107",
      onWarning: "#856404",
      warningContainer: "#F8F8F8",
      onWarningContainer: "#fff3cd",
      error: "#F04438",
      onError: "#F8F8F8",
      errorContainer: "#F8F8F8",
      onErrorContainer: "#ffd6d6",
      info: "#17a2b8",
      onInfo: "#0c5460",
      infoContainer: "#0c5460",
      onInfoContainer: "#d1ecf1",
      disabledSurface: "rgba(229, 231, 235, 0.12)",
      disabledContent: "rgba(229, 231, 235, 0.38)",
      placeholder: "#A0A7B0",
      pressed: "#F0F8F4",
      selected: "#ECFDF3",
      elevation: {
        level0: "transparent",
        level1: "#1f2937",
        level2: "#374151",
        level3: "#4b5563",
        level4: "#6b7280",
        level5: "#9ca3af",
      },
      diet: {
        primaryText: "#0B2A22",
        secondaryText: "#4B5563",
        tertiaryText: "#4B7A62",
        card: "#FFFFFF",
        cardSubtle: "#F5F8F6",
        border: "rgba(15, 94, 59, 0.08)",
        borderStrong: "#86EFAC",
        mint: "#E8F5EF",
        mintStrong: "#F0FDF4",
        consumedBackground: "#DCFCE7",
        consumedBorder: "#BBF7D0",
        consumedText: "#166534",
        dangerBackground: "#FFF1F2",
        dangerBorder: "#DC2626",
        dangerText: "#B42318",
      },
      steps: {
        aboveGoalDark: "#2EB94D",
        aboveGoal: "#4ED167",
        aboveGoalLight: "#C7F0CB",
        belowGoalDark: "#DC6E4A",
        belowGoal: "#E88E72",
        belowGoalLight: "#F4C4B5",
        ringTrack: "#E4E7EC",
        ringGradientStart: "#072723",
        ringGradientEnd: "#9FE6A3",
        mutedText: "rgba(7,39,35,0.55)",
        mutedTextSoft: "rgba(7,39,35,0.6)",
        mutedTextFaint: "rgba(7,39,35,0.45)",
        hairline: "rgba(7,39,35,0.08)",
        baseline: "rgba(7,39,35,0.12)",
        target: "rgba(7,39,35,0.3)",
        dayLabel: "rgba(7,39,35,0.75)",
        selectedPill: "rgba(7,39,35,0.08)",
      },
      graph: {
        line: "rgba(119, 243, 146, 1)",
        lineSecondary: "#454459",
        gradientStart: "#9FFFA2",
        gradientEnd: "#79F681",
        gradientStartTransparent: "rgba(159, 255, 162, 0.2)",
        gradientEndTransparent: "rgba(121, 246, 129, 0.05)",
        dot: "#33B333",
        dotBorder: "#FFFFFF",
        label: "rgba(69, 68, 89, 0.5)",
        tooltip: "#79F681",
        tooltipText: "#000000",
        tooltipShadow: "rgba(0,0,0,0.35)",
      },
      calendar: {
        dayHeader: "#000000",
        today: "#E0E0E0",
        agendaText: "#2d4150",
        selected: "#0000FF",
        dot: "#FFBC5D",
        dotSelected: "#FFA500",
      },
      scanner: {
        background: "#07110E",
        headerOverlay: "rgba(7, 17, 14, 0.72)",
        controlSurface: "rgba(255, 255, 255, 0.16)",
        controlBorder: "rgba(255, 255, 255, 0.24)",
        viewfinder: "#5BE29B",
        scanLine: "#5BE29B",
        panel: "#FFFFFF",
        panelText: "#6B7280",
        successOverlay: "rgba(7, 46, 34, 0.78)",
        dimOverlay: "rgba(7, 17, 14, 0.62)",
      },
      overlay: {
        imageSurface: "rgba(255, 255, 255, 0.92)",
        imageShadow: "#000000",
        modal: "rgba(5, 20, 16, 0.48)",
        modalStrong: "rgba(9, 29, 22, 0.3)",
        translucentSurface: "rgba(255, 255, 255, 0.22)",
      },
    },
  },
  permissions: {
    camera: CAMERA_PERMISSION,
    photos: "The app accesses your photos to let you share them with your friends.",
    healthShare:
      "כדי לעקוב אחרי הצעדים שלך, האפליקציה צריכה גישה לנתוני הצעדים והפעילות מאפליקציית הבריאות.",
    healthUpdate: "האפליקציה לא משנה נתונים באפליקציית הבריאות.",
    android: [
      "android.permission.health.READ_HEALTH_DATA_IN_BACKGROUND",
      "android.permission.health.READ_STEPS",
    ],
  },
  androidBuildProperties: {
    compileSdkVersion: 36,
    targetSdkVersion: 36,
    minSdkVersion: 26,
    enableProguardInReleaseBuilds: true,
    enableShrinkResourcesInReleaseBuilds: true,
  },
  localization: {
    supportsRtl: true,
    forcesRtl: true,
  },
  featureDefaults: {
    articles: true,
    chat: true,
    dietPlan: true,
    smartFoodCatalog: true,
    workoutPlan: true,
    stepTracking: true,
    progressTracking: true,
    formsAndAgreements: true,
    mediaCapture: true,
    notifications: true,
  },
  nativeCapabilities: {
    camera: true,
    photoLibrary: true,
    notifications: true,
    backgroundTasks: true,
    appleHealth: true,
    healthConnect: true,
    liveActivities: true,
  },
  requiredEnvironmentVariables: {
    development: REQUIRED_PUBLIC_ENVIRONMENT_VARIABLES,
    preview: [...REQUIRED_PUBLIC_ENVIRONMENT_VARIABLES, "EXPO_PUBLIC_API_URL_PREVIEW"],
    production: REQUIRED_PUBLIC_ENVIRONMENT_VARIABLES,
  },
  environments: {
    development: {
      iosBundleIdentifier: "com.avihuteam.avihuteam.dev",
      androidPackage: "com.avihuteam.avihuteam.dev",
      scheme: "avihuteam",
      allowSharedStoreIdentity: false,
    },
    preview: {
      iosBundleIdentifier: "com.avihuteam.avihuteam",
      androidPackage: "com.avihuteam.avihuteam",
      scheme: "avihuteam",
      allowSharedStoreIdentity: true,
    },
    production: {
      iosBundleIdentifier: "com.avihuteam.avihuteam",
      androidPackage: "com.avihuteam.avihuteam",
      scheme: "avihuteam",
      allowSharedStoreIdentity: true,
    },
  },
} satisfies TenantConfig;
