import { z } from "zod";

const colorSchema = z
  .string()
  .refine(
    (value) =>
      value === "transparent" ||
      /^#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?$/.test(value) ||
      /^(?:rgb|hsl)a?\([^)]+\)$/.test(value),
    { message: "Expected a hex, rgb, hsl, or transparent color" }
  );

const colorObject = <Shape extends z.ZodRawShape>(shape: Shape) => z.object(shape).strict();

export const tenantThemeSchema = colorObject({
  colors: colorObject({
    primary: colorSchema,
    onPrimary: colorSchema,
    secondary: colorSchema,
    onSecondary: colorSchema,
    accent: colorSchema,
    onAccent: colorSchema,
    primaryContainer: colorSchema,
    onPrimaryContainer: colorSchema,
    secondaryContainer: colorSchema,
    onSecondaryContainer: colorSchema,
    background: colorSchema,
    onBackground: colorSchema,
    surface: colorSchema,
    onSurface: colorSchema,
    surfaceSubtle: colorSchema,
    surfaceMuted: colorSchema,
    surfaceVariant: colorSchema,
    onSurfaceVariant: colorSchema,
    outline: colorSchema,
    outlineVariant: colorSchema,
    divider: colorSchema,
    shadow: colorSchema,
    shadowMuted: colorSchema,
    scrim: colorSchema,
    backdrop: colorSchema,
    inverseSurface: colorSchema,
    inverseOnSurface: colorSchema,
    inversePrimary: colorSchema,
    success: colorSchema,
    onSuccess: colorSchema,
    successContainer: colorSchema,
    onSuccessContainer: colorSchema,
    warning: colorSchema,
    onWarning: colorSchema,
    warningContainer: colorSchema,
    onWarningContainer: colorSchema,
    error: colorSchema,
    onError: colorSchema,
    errorContainer: colorSchema,
    onErrorContainer: colorSchema,
    info: colorSchema,
    onInfo: colorSchema,
    infoContainer: colorSchema,
    onInfoContainer: colorSchema,
    disabledSurface: colorSchema,
    disabledContent: colorSchema,
    placeholder: colorSchema,
    pressed: colorSchema,
    selected: colorSchema,
    elevation: colorObject({
      level0: colorSchema,
      level1: colorSchema,
      level2: colorSchema,
      level3: colorSchema,
      level4: colorSchema,
      level5: colorSchema,
    }),
    diet: colorObject({
      primaryText: colorSchema,
      secondaryText: colorSchema,
      tertiaryText: colorSchema,
      card: colorSchema,
      cardSubtle: colorSchema,
      border: colorSchema,
      borderStrong: colorSchema,
      mint: colorSchema,
      mintStrong: colorSchema,
      consumedBackground: colorSchema,
      consumedBorder: colorSchema,
      consumedText: colorSchema,
      dangerBackground: colorSchema,
      dangerBorder: colorSchema,
      dangerText: colorSchema,
    }),
    steps: colorObject({
      aboveGoalDark: colorSchema,
      aboveGoal: colorSchema,
      aboveGoalLight: colorSchema,
      belowGoalDark: colorSchema,
      belowGoal: colorSchema,
      belowGoalLight: colorSchema,
      ringTrack: colorSchema,
      ringGradientStart: colorSchema,
      ringGradientEnd: colorSchema,
      mutedText: colorSchema,
      mutedTextSoft: colorSchema,
      mutedTextFaint: colorSchema,
      hairline: colorSchema,
      baseline: colorSchema,
      target: colorSchema,
      dayLabel: colorSchema,
      selectedPill: colorSchema,
    }),
    graph: colorObject({
      line: colorSchema,
      lineSecondary: colorSchema,
      gradientStart: colorSchema,
      gradientEnd: colorSchema,
      gradientStartTransparent: colorSchema,
      gradientEndTransparent: colorSchema,
      dot: colorSchema,
      dotBorder: colorSchema,
      label: colorSchema,
      tooltip: colorSchema,
      tooltipText: colorSchema,
      tooltipShadow: colorSchema,
    }),
    calendar: colorObject({
      dayHeader: colorSchema,
      today: colorSchema,
      agendaText: colorSchema,
      selected: colorSchema,
      dot: colorSchema,
      dotSelected: colorSchema,
    }),
    scanner: colorObject({
      background: colorSchema,
      headerOverlay: colorSchema,
      controlSurface: colorSchema,
      controlBorder: colorSchema,
      viewfinder: colorSchema,
      scanLine: colorSchema,
      panel: colorSchema,
      panelText: colorSchema,
      successOverlay: colorSchema,
      dimOverlay: colorSchema,
    }),
    overlay: colorObject({
      imageSurface: colorSchema,
      imageShadow: colorSchema,
      modal: colorSchema,
      modalStrong: colorSchema,
      translucentSurface: colorSchema,
    }),
  }),
});

export type TenantTheme = z.infer<typeof tenantThemeSchema>;
