import { z } from "zod";

export const tenantColorSchema = z
  .string()
  .refine(
    (value) =>
      value === "transparent" ||
      /^#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?$/.test(value) ||
      /^(?:rgb|hsl)a?\([^)]+\)$/.test(value),
    { message: "Expected a hex, rgb, hsl, or transparent color" }
  );

const colorObject = <Shape extends z.ZodRawShape>(shape: Shape) => z.object(shape).strict();

export const tenantThemeColorsSchema = colorObject({
  primary: tenantColorSchema,
  onPrimary: tenantColorSchema,
  secondary: tenantColorSchema,
  onSecondary: tenantColorSchema,
  accent: tenantColorSchema,
  onAccent: tenantColorSchema,
  tertiary: tenantColorSchema,
  onTertiary: tenantColorSchema,
  tertiaryContainer: tenantColorSchema,
  onTertiaryContainer: tenantColorSchema,
  primaryContainer: tenantColorSchema,
  onPrimaryContainer: tenantColorSchema,
  secondaryContainer: tenantColorSchema,
  onSecondaryContainer: tenantColorSchema,
  background: tenantColorSchema,
  onBackground: tenantColorSchema,
  surface: tenantColorSchema,
  onSurface: tenantColorSchema,
  surfaceSubtle: tenantColorSchema,
  surfaceMuted: tenantColorSchema,
  surfaceVariant: tenantColorSchema,
  onSurfaceVariant: tenantColorSchema,
  outline: tenantColorSchema,
  outlineVariant: tenantColorSchema,
  divider: tenantColorSchema,
  shadow: tenantColorSchema,
  shadowMuted: tenantColorSchema,
  scrim: tenantColorSchema,
  backdrop: tenantColorSchema,
  inverseSurface: tenantColorSchema,
  inverseOnSurface: tenantColorSchema,
  inversePrimary: tenantColorSchema,
  success: tenantColorSchema,
  onSuccess: tenantColorSchema,
  successContainer: tenantColorSchema,
  onSuccessContainer: tenantColorSchema,
  warning: tenantColorSchema,
  onWarning: tenantColorSchema,
  warningContainer: tenantColorSchema,
  onWarningContainer: tenantColorSchema,
  error: tenantColorSchema,
  onError: tenantColorSchema,
  errorContainer: tenantColorSchema,
  onErrorContainer: tenantColorSchema,
  info: tenantColorSchema,
  onInfo: tenantColorSchema,
  infoContainer: tenantColorSchema,
  onInfoContainer: tenantColorSchema,
  surfaceDisabled: tenantColorSchema,
  onSurfaceDisabled: tenantColorSchema,
  placeholder: tenantColorSchema,
  pressed: tenantColorSchema,
  selected: tenantColorSchema,
  elevation: colorObject({
    level0: tenantColorSchema,
    level1: tenantColorSchema,
    level2: tenantColorSchema,
    level3: tenantColorSchema,
    level4: tenantColorSchema,
    level5: tenantColorSchema,
  }),
  diet: colorObject({
    primaryText: tenantColorSchema,
    secondaryText: tenantColorSchema,
    tertiaryText: tenantColorSchema,
    card: tenantColorSchema,
    cardSubtle: tenantColorSchema,
    border: tenantColorSchema,
    borderStrong: tenantColorSchema,
    mint: tenantColorSchema,
    mintStrong: tenantColorSchema,
    consumedBackground: tenantColorSchema,
    consumedBorder: tenantColorSchema,
    consumedText: tenantColorSchema,
    dangerBackground: tenantColorSchema,
    dangerBorder: tenantColorSchema,
    dangerText: tenantColorSchema,
  }),
  steps: colorObject({
    aboveGoalDark: tenantColorSchema,
    aboveGoal: tenantColorSchema,
    aboveGoalLight: tenantColorSchema,
    belowGoalDark: tenantColorSchema,
    belowGoal: tenantColorSchema,
    belowGoalLight: tenantColorSchema,
    ringTrack: tenantColorSchema,
    ringGradientStart: tenantColorSchema,
    ringGradientEnd: tenantColorSchema,
    mutedText: tenantColorSchema,
    mutedTextSoft: tenantColorSchema,
    mutedTextFaint: tenantColorSchema,
    hairline: tenantColorSchema,
    baseline: tenantColorSchema,
    target: tenantColorSchema,
    dayLabel: tenantColorSchema,
    selectedPill: tenantColorSchema,
  }),
  graph: colorObject({
    line: tenantColorSchema,
    lineSecondary: tenantColorSchema,
    gradientStart: tenantColorSchema,
    gradientEnd: tenantColorSchema,
    gradientStartTransparent: tenantColorSchema,
    gradientEndTransparent: tenantColorSchema,
    dot: tenantColorSchema,
    dotBorder: tenantColorSchema,
    label: tenantColorSchema,
    tooltip: tenantColorSchema,
    tooltipText: tenantColorSchema,
    tooltipShadow: tenantColorSchema,
  }),
  calendar: colorObject({
    dayHeader: tenantColorSchema,
    today: tenantColorSchema,
    agendaText: tenantColorSchema,
    selected: tenantColorSchema,
    dot: tenantColorSchema,
    dotSelected: tenantColorSchema,
  }),
  scanner: colorObject({
    background: tenantColorSchema,
    headerOverlay: tenantColorSchema,
    controlSurface: tenantColorSchema,
    controlBorder: tenantColorSchema,
    viewfinder: tenantColorSchema,
    scanLine: tenantColorSchema,
    panel: tenantColorSchema,
    panelText: tenantColorSchema,
    successOverlay: tenantColorSchema,
    dimOverlay: tenantColorSchema,
  }),
  overlay: colorObject({
    imageSurface: tenantColorSchema,
    imageShadow: tenantColorSchema,
    modal: tenantColorSchema,
    modalStrong: tenantColorSchema,
    translucentSurface: tenantColorSchema,
  }),
  app: colorObject({
    textStrong: tenantColorSchema,
    textDefault: tenantColorSchema,
    textMuted: tenantColorSchema,
    textSubtle: tenantColorSchema,
    textSlate: tenantColorSchema,
    textForm: tenantColorSchema,
    textPlaceholder: tenantColorSchema,
    textAgreement: tenantColorSchema,
    neutralGray: tenantColorSchema,
    surfaceRaised: tenantColorSchema,
    surfacePanel: tenantColorSchema,
    surfaceSoft: tenantColorSchema,
    surfaceCool: tenantColorSchema,
    surfaceWarm: tenantColorSchema,
    borderSoft: tenantColorSchema,
    borderControl: tenantColorSchema,
    borderHandle: tenantColorSchema,
    formBorder: tenantColorSchema,
    brandStrong: tenantColorSchema,
    brandAction: tenantColorSchema,
    brandSuccess: tenantColorSchema,
    brandPressed: tenantColorSchema,
    developerSuccessText: tenantColorSchema,
    developerSuccessSurface: tenantColorSchema,
    developerWarningText: tenantColorSchema,
    developerWarningSurface: tenantColorSchema,
    developerErrorSurface: tenantColorSchema,
    articleLiked: tenantColorSchema,
    notificationAccent: tenantColorSchema,
    dietSuccessBorder: tenantColorSchema,
    dietSuccessSurface: tenantColorSchema,
    dietSuccessText: tenantColorSchema,
    dietProgressTrack: tenantColorSchema,
    dietWhatsapp: tenantColorSchema,
    dietInfo: tenantColorSchema,
    dietPositive: tenantColorSchema,
    dietNegativeSoft: tenantColorSchema,
    dietNeutralBorder: tenantColorSchema,
    dietMutedBorder: tenantColorSchema,
    dietSearchIcon: tenantColorSchema,
    dietSearchSurface: tenantColorSchema,
    dietSearchBorder: tenantColorSchema,
    dietSearchDivider: tenantColorSchema,
    dietSearchDisabled: tenantColorSchema,
    dietSearchIconMuted: tenantColorSchema,
    dietSearchAttribution: tenantColorSchema,
    dietInputBorder: tenantColorSchema,
    dietInputErrorSurface: tenantColorSchema,
    dietSectionBorder: tenantColorSchema,
    dietSectionDivider: tenantColorSchema,
    dietTabBorder: tenantColorSchema,
    dietResultSurface: tenantColorSchema,
    dietHistorySurface: tenantColorSchema,
    dietServingSurface: tenantColorSchema,
    dietServingBorder: tenantColorSchema,
    dietCardShadow: tenantColorSchema,
    dietDividerDark: tenantColorSchema,
    dietSelection: tenantColorSchema,
    dietMutedText: tenantColorSchema,
    dietAttributionPressed: tenantColorSchema,
    scannerHoldOverlay: tenantColorSchema,
    scannerSuccessText: tenantColorSchema,
    scannerErrorSurface: tenantColorSchema,
    formExit: tenantColorSchema,
    dangerPure: tenantColorSchema,
    graphIndicator: tenantColorSchema,
    graphLabelStrong: tenantColorSchema,
    graphHighlightStroke: tenantColorSchema,
    agreementBorder: tenantColorSchema,
    agreementSurface: tenantColorSchema,
    agreementSurfaceStrong: tenantColorSchema,
    shadowHairline: tenantColorSchema,
    shadowSoft: tenantColorSchema,
    shadowMedium: tenantColorSchema,
    shadowStrong: tenantColorSchema,
    shadowTrace: tenantColorSchema,
    drawerOverlay: tenantColorSchema,
    translucentWhite: tenantColorSchema,
    translucentWhiteFaint: tenantColorSchema,
    transparentBackground: tenantColorSchema,
    stepsHeaderMuted: tenantColorSchema,
    updateOverlay: tenantColorSchema,
  }),
});

export const tenantThemeSchema = colorObject({ colors: tenantThemeColorsSchema });

export type TenantTheme = z.infer<typeof tenantThemeSchema>;
