export const E2E_TEST_IDS = {
  loginRoot: "e2e-login-root",
  loginEmail: "e2e-login-email",
  loginEmailError: "e2e-login-email-error",
  loginPassword: "e2e-login-password",
  loginPasswordError: "e2e-login-password-error",
  loginSubmit: "e2e-login-submit",
  forgotPasswordOpen: "e2e-forgot-password-open",
  forgotPasswordRoot: "e2e-forgot-password-root",
  forgotPasswordEmail: "e2e-forgot-password-email",
  forgotPasswordEmailError: "e2e-forgot-password-email-error",
  forgotPasswordSubmit: "e2e-forgot-password-submit",
  forgotPasswordBack: "e2e-forgot-password-back",
  otpInput: "e2e-otp-input",
  otpError: "e2e-otp-error",
  otpSubmit: "e2e-otp-submit",
  toastError: "e2e-toast-error",
  environmentBadge: "e2e-environment-badge",
  homeRoot: "e2e-home-root",
  tabHome: "e2e-tab-home",
  tabWorkout: "e2e-tab-workout",
  workoutRoot: "e2e-workout-root",
  tabDiet: "e2e-tab-diet",
  dietRoot: "e2e-diet-root",
  profileOpen: "e2e-profile-open",
  profileRoot: "e2e-profile-root",
  logout: "e2e-logout",
} as const;
